// MC-020 — Ingredient seed catalog (300 ingredients).
//
// 8 categories, 300 ingredients. Schema: see Ingredient in
// prisma/schema.prisma (canonicalName is unique; aliases live in
// IngredientAlias with `(alias, locale)` PK).
//
// Money is Int kopecks (PM-prompt #5). Float fields are kept
// here only for density / ediblePartRatio (ADR-0011).

export type CategorySlug =
  'VEGETABLE' | 'FRUIT' | 'MEAT' | 'DAIRY' | 'GRAIN' | 'SPICE' | 'BEVERAGE' | 'OTHER';

export type UnitSlug = 'G' | 'ML' | 'PIECE';

export interface IngredientSeed {
  canonicalName: string;
  category: CategorySlug;
  defaultUnit: UnitSlug;
  packageSize: number; // grams or millilitres per store package
  avgPriceKopecks: number; // 1 kopeck = 0.01 RUB; 8000 = 80 ₽
  defaultShelfDaysFridge: number | null;
  defaultShelfDaysPantry: number | null;
  defaultShelfDaysFreezer: number | null;
  density: number | null; // g/ml
  ediblePartRatio: number; // 0..1, defaults to 1.0 in schema
  aliases: readonly string[];
}

export const INGREDIENTS: readonly IngredientSeed[] = [
  {
    canonicalName: 'помидор',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['томат', 'томаты', 'pomidor'],
  },
  {
    canonicalName: 'огурец',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 7000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: null,
    density: 0.97,
    ediblePartRatio: 0.97,
    aliases: [],
  },
  {
    canonicalName: 'перец болгарский',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.5,
    ediblePartRatio: 0.85,
    aliases: ['болгарский перец', 'сладкий перец'],
  },
  {
    canonicalName: 'лук репчатый',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 3000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.92,
    ediblePartRatio: 0.9,
    aliases: ['репчатый лук', 'лук'],
  },
  {
    canonicalName: 'лук красный',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.92,
    ediblePartRatio: 0.9,
    aliases: ['красный лук'],
  },
  {
    canonicalName: 'чеснок',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 4000,
    defaultShelfDaysFridge: 60,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.85,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'морковь',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 4000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.96,
    ediblePartRatio: 0.9,
    aliases: [],
  },
  {
    canonicalName: 'картофель',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 6000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['картошка', 'картофель молодой', 'молодой картофель'],
  },
  {
    canonicalName: 'капуста белокочанная',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.93,
    ediblePartRatio: 0.85,
    aliases: ['белокочанная капуста', 'капуста'],
  },
  {
    canonicalName: 'капуста цветная',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.92,
    ediblePartRatio: 0.8,
    aliases: ['цветная капуста'],
  },
  {
    canonicalName: 'брокколи',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.92,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'свёкла',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 4000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.97,
    ediblePartRatio: 0.85,
    aliases: ['свекла'],
  },
  {
    canonicalName: 'кабачок',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['цукини'],
  },
  {
    canonicalName: 'баклажан',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.93,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'тыква',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'редис',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 6000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: null,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'редька',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'шпинат',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'щавель',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'петрушка',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'укроп',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'базилик',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['зеленый базилик'],
  },
  {
    canonicalName: 'салат айсберг',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: null,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['айсберг', 'салат'],
  },
  {
    canonicalName: 'руккола',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 20000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'авокадо',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.92,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'перец чили',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.93,
    ediblePartRatio: 0.85,
    aliases: ['чили'],
  },
  {
    canonicalName: 'имбирь',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['свежий имбирь'],
  },
  {
    canonicalName: 'батат',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.96,
    ediblePartRatio: 0.85,
    aliases: ['сладкий картофель'],
  },
  {
    canonicalName: 'кукуруза',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 7000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.7,
    aliases: [],
  },
  {
    canonicalName: 'горошек зелёный',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.92,
    ediblePartRatio: 0.85,
    aliases: ['зеленый горошек'],
  },
  {
    canonicalName: 'фасоль стручковая',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 14000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.92,
    ediblePartRatio: 0.85,
    aliases: ['спаржевая фасоль'],
  },
  {
    canonicalName: 'помидоры черри',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['черри'],
  },
  {
    canonicalName: 'репа',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.96,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'брюква',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.96,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'патиссон',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 60,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'артишок',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.93,
    ediblePartRatio: 0.6,
    aliases: [],
  },
  {
    canonicalName: 'фенхель',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'лук-порей',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['порей'],
  },
  {
    canonicalName: 'мангольд',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'сельдерей',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 60,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'хрен',
    category: 'VEGETABLE',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'яблоко',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 7000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 365,
    density: 0.85,
    ediblePartRatio: 0.92,
    aliases: ['яблоки'],
  },
  {
    canonicalName: 'банан',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.94,
    ediblePartRatio: 0.7,
    aliases: ['бананы'],
  },
  {
    canonicalName: 'апельсин',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 21,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 365,
    density: 0.9,
    ediblePartRatio: 0.8,
    aliases: ['апельсины'],
  },
  {
    canonicalName: 'лимон',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 60,
    defaultShelfDaysFreezer: 180,
    density: 0.92,
    ediblePartRatio: 0.7,
    aliases: ['лимоны'],
  },
  {
    canonicalName: 'лайм',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 21,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 0.92,
    ediblePartRatio: 0.7,
    aliases: [],
  },
  {
    canonicalName: 'грейпфрут',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 21,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 365,
    density: 0.9,
    ediblePartRatio: 0.7,
    aliases: [],
  },
  {
    canonicalName: 'груша',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 0.92,
    ediblePartRatio: 0.9,
    aliases: ['груши'],
  },
  {
    canonicalName: 'персик',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.93,
    ediblePartRatio: 0.85,
    aliases: ['персики'],
  },
  {
    canonicalName: 'нектарин',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.93,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'абрикос',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.93,
    ediblePartRatio: 0.85,
    aliases: ['абрикосы'],
  },
  {
    canonicalName: 'слива',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.93,
    ediblePartRatio: 0.85,
    aliases: ['сливы'],
  },
  {
    canonicalName: 'вишня',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['вишни'],
  },
  {
    canonicalName: 'черешня',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'клубника',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'малина',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'ежевика',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'голубика',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 45000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['блюберри'],
  },
  {
    canonicalName: 'черника',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 45000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'смородина чёрная',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['черная смородина'],
  },
  {
    canonicalName: 'крыжовник',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'виноград',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'арбуз',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 2000,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: null,
    density: 0.95,
    ediblePartRatio: 0.6,
    aliases: [],
  },
  {
    canonicalName: 'дыня',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 2000,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: null,
    density: 0.95,
    ediblePartRatio: 0.6,
    aliases: [],
  },
  {
    canonicalName: 'ананас',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.6,
    aliases: [],
  },
  {
    canonicalName: 'манго',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.7,
    aliases: [],
  },
  {
    canonicalName: 'киви',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 0.93,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'папайя',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.7,
    aliases: [],
  },
  {
    canonicalName: 'гранат',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 21,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.65,
    aliases: [],
  },
  {
    canonicalName: 'хурма',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'инжир',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'финики',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['финик'],
  },
  {
    canonicalName: 'курага',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'изюм',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'клюква',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'брусника',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'облепиха',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'шиповник',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'айва',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.93,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'мушмула',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'фейхоа',
    category: 'FRUIT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 35000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'курица (грудка)',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['куриная грудка', 'филе курицы'],
  },
  {
    canonicalName: 'курица (бедро)',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['куриное бедро'],
  },
  {
    canonicalName: 'индейка (грудка)',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['грудка индейки', 'филе индейки'],
  },
  {
    canonicalName: 'индейка (бедро)',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 22000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['бедро индейки'],
  },
  {
    canonicalName: 'утка',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'гусь',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 35000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'говядина (вырезка)',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 65000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['говяжья вырезка', 'вырезка'],
  },
  {
    canonicalName: 'говядина (лопатка)',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 45000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['говяжья лопатка'],
  },
  {
    canonicalName: 'говядина (фарш)',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: 1,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: ['говяжий фарш', 'фарш'],
  },
  {
    canonicalName: 'свинина (вырезка)',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['свиная вырезка'],
  },
  {
    canonicalName: 'свинина (фарш)',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 1,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: ['свиной фарш'],
  },
  {
    canonicalName: 'баранина',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 60000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'телятина',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 70000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'кролик',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 45000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'печень говяжья',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['говяжья печень'],
  },
  {
    canonicalName: 'сердце говяжье',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 22000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['говяжье сердце'],
  },
  {
    canonicalName: 'почки',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'язык',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'сало',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 0.92,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'бекон',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 45000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'ветчина',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 45000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'колбаса вареная',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: null,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['вареная колбаса', 'докторская'],
  },
  {
    canonicalName: 'колбаса копчёная',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 35000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: null,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['копченая колбаса'],
  },
  {
    canonicalName: 'сосиски',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'пельмени',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 90,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'котлеты',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: [],
  },
  {
    canonicalName: 'фарш куриный',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 1,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: ['куриный фарш'],
  },
  {
    canonicalName: 'фарш свиной',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 1,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'фарш говяжий',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: 1,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'фарш индейки',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 28000,
    defaultShelfDaysFridge: 1,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'шашлык бараний',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 60000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['шашлык'],
  },
  {
    canonicalName: 'куриные крылышки',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['крылышки'],
  },
  {
    canonicalName: 'куриные бёдра',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'свиные рёбра',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 35000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['ребра свиные'],
  },
  {
    canonicalName: 'баранина на кости',
    category: 'MEAT',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 55000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'молоко (коровье)',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 1000,
    avgPriceKopecks: 7000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.03,
    ediblePartRatio: 1.0,
    aliases: ['молоко', 'коровье молоко', 'молоко 3', '2%'],
  },
  {
    canonicalName: 'молоко (козье)',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.03,
    ediblePartRatio: 1.0,
    aliases: ['козье молоко'],
  },
  {
    canonicalName: 'молоко (овсяное)',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: null,
    density: 1.04,
    ediblePartRatio: 1.0,
    aliases: ['овсяное молоко'],
  },
  {
    canonicalName: 'сливки 10%',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.01,
    ediblePartRatio: 1.0,
    aliases: ['сливки'],
  },
  {
    canonicalName: 'сливки 20%',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.01,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'сливки 33%',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.0,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'сметана 15%',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: null,
    density: 0.97,
    ediblePartRatio: 1.0,
    aliases: ['сметана'],
  },
  {
    canonicalName: 'сметана 20%',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 14000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: null,
    density: 0.97,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'кефир 1%',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 7000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: null,
    density: 1.03,
    ediblePartRatio: 1.0,
    aliases: ['кефир'],
  },
  {
    canonicalName: 'кефир 3,2%',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: null,
    density: 1.03,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'ряженка',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: null,
    density: 1.03,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'творог 5%',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['творог'],
  },
  {
    canonicalName: 'творог 9%',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 14000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'творог обезжиренный',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['обезжиренный творог'],
  },
  {
    canonicalName: 'сыр Российский',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 35000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['российский сыр'],
  },
  {
    canonicalName: 'сыр Гауда',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 45000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 60,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['гауда'],
  },
  {
    canonicalName: 'сыр Чеддер',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 45000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 60,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['чеддер'],
  },
  {
    canonicalName: 'сыр Пармезан',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 80000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['пармезан'],
  },
  {
    canonicalName: 'сыр Моцарелла',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['моцарелла'],
  },
  {
    canonicalName: 'сыр Фета',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['фета'],
  },
  {
    canonicalName: 'сыр Бри',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 65000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 30,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['бри'],
  },
  {
    canonicalName: 'сыр Дор Блю',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 70000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 60,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['дорблю', 'дор блю'],
  },
  {
    canonicalName: 'масло сливочное',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.91,
    ediblePartRatio: 1.0,
    aliases: ['сливочное масло', 'масло', 'сливочное'],
  },
  {
    canonicalName: 'маргарин',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.91,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'яйцо куриное',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 600,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 21,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.03,
    ediblePartRatio: 0.9,
    aliases: ['яйца', 'яйцо', 'куриное яйцо'],
  },
  {
    canonicalName: 'яйцо перепелиное',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 21,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.03,
    ediblePartRatio: 0.9,
    aliases: ['яйца перепелиные', 'перепелиное яйцо'],
  },
  {
    canonicalName: 'яйцо страусиное',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.03,
    ediblePartRatio: 0.9,
    aliases: [],
  },
  {
    canonicalName: 'йогурт натуральный',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['натуральный йогурт', 'йогурт'],
  },
  {
    canonicalName: 'йогурт греческий',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['греческий йогурт'],
  },
  {
    canonicalName: 'сметана 25%',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 16000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: null,
    density: 0.97,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'простокваша',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: null,
    density: 1.03,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'кефир обезжиренный',
    category: 'DAIRY',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 7000,
    defaultShelfDaysFridge: 5,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: null,
    density: 1.03,
    ediblePartRatio: 1.0,
    aliases: ['обезжиренный кефир'],
  },
  {
    canonicalName: 'сыр Рикотта',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['рикотта'],
  },
  {
    canonicalName: 'сыр Маскарпоне',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 50000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['маскарпоне'],
  },
  {
    canonicalName: 'сгущёнка',
    category: 'DAIRY',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.1,
    ediblePartRatio: 1.0,
    aliases: ['сгущенка', 'сгущенное молоко'],
  },
  {
    canonicalName: 'рис белый',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: ['рис'],
  },
  {
    canonicalName: 'рис бурый',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: ['бурый рис'],
  },
  {
    canonicalName: 'рис басмати',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: ['басмати'],
  },
  {
    canonicalName: 'гречка',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: ['гречневая крупа'],
  },
  {
    canonicalName: 'овсянка',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.65,
    ediblePartRatio: 1.0,
    aliases: ['овсяные хлопья', 'геркулес'],
  },
  {
    canonicalName: 'пшено',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 7000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: ['пшенная крупа'],
  },
  {
    canonicalName: 'перловка',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 6000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: ['перловая крупа'],
  },
  {
    canonicalName: 'булгур',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'кускус',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'киноа',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'макароны',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 7000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'спагетти',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'пенне',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 9000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: ['пенне'],
  },
  {
    canonicalName: 'фузилли',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 9000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'лапша рисовая',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: ['рисовая лапша'],
  },
  {
    canonicalName: 'лапша яичная',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: ['яичная лапша'],
  },
  {
    canonicalName: 'лапша удон',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: ['удон'],
  },
  {
    canonicalName: 'хлеб белый',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: 5,
    defaultShelfDaysFreezer: 180,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: ['белый хлеб'],
  },
  {
    canonicalName: 'хлеб чёрный',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 6000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: 5,
    defaultShelfDaysFreezer: 180,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: ['черный хлеб', 'бородинский'],
  },
  {
    canonicalName: 'батон',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: 5,
    defaultShelfDaysFreezer: 180,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'багет',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 2,
    defaultShelfDaysPantry: 3,
    defaultShelfDaysFreezer: 180,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'круассан',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 1,
    defaultShelfDaysPantry: 3,
    defaultShelfDaysFreezer: 180,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'сушки',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'печенье',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'крекер',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 300,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'гранола',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.65,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'мюсли',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 20000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 0.65,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'толокно',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.65,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'мука пшеничная',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 7000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.6,
    ediblePartRatio: 1.0,
    aliases: ['пшеничная мука', 'мука'],
  },
  {
    canonicalName: 'мука ржаная',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.6,
    ediblePartRatio: 1.0,
    aliases: ['ржаная мука'],
  },
  {
    canonicalName: 'мука кукурузная',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.6,
    ediblePartRatio: 1.0,
    aliases: ['кукурузная мука'],
  },
  {
    canonicalName: 'крахмал картофельный',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 0.6,
    ediblePartRatio: 1.0,
    aliases: ['картофельный крахмал'],
  },
  {
    canonicalName: 'сухари панировочные',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 90,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.6,
    ediblePartRatio: 1.0,
    aliases: ['панировочные сухари'],
  },
  {
    canonicalName: 'кукурузные хлопья',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: ['хлопья кукурузные'],
  },
  {
    canonicalName: '떡',
    category: 'GRAIN',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: null,
    defaultShelfDaysFreezer: 180,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['рисовый тток'],
  },
  {
    canonicalName: 'соль',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 3000,
    defaultShelfDaysFridge: 1825,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 1.2,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'перец чёрный',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['черный перец'],
  },
  {
    canonicalName: 'перец красный',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['красный перец'],
  },
  {
    canonicalName: 'паприка',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'куркума',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'корица',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['молотая корица'],
  },
  {
    canonicalName: 'кориандр молотый',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['молотый кориандр', 'кориандр'],
  },
  {
    canonicalName: 'мускатный орех',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['мускат'],
  },
  {
    canonicalName: 'гвоздика',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'лавровый лист',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['лаврушка'],
  },
  {
    canonicalName: 'базилик сушёный',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['сушеный базилик'],
  },
  {
    canonicalName: 'орегано',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'тимьян',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'розмарин',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'мята сушёная',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['сушеная мята'],
  },
  {
    canonicalName: 'шафран',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 10,
    avgPriceKopecks: 80000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'карри',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'чили молотый',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['молотый чили'],
  },
  {
    canonicalName: 'копчёная паприка',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['копченая паприка', 'пиментон'],
  },
  {
    canonicalName: 'хмели-сунели',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['хмели сунели'],
  },
  {
    canonicalName: 'аджика',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'горчица',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['горчица зерна', 'горчичный порошок'],
  },
  {
    canonicalName: 'ваниль',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 35000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['ванильный стручок'],
  },
  {
    canonicalName: 'кардамон',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'кумин',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['зира'],
  },
  {
    canonicalName: 'тмин',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'анис',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'сумах',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['сумак'],
  },
  {
    canonicalName: 'бадьян',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['звёздчатый анис'],
  },
  {
    canonicalName: 'майоран',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'эстрагон',
    category: 'SPICE',
    defaultUnit: 'G',
    packageSize: 50,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['тархун'],
  },
  {
    canonicalName: 'вода',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 2000,
    avgPriceKopecks: 2000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 365,
    density: 1.0,
    ediblePartRatio: 1.0,
    aliases: ['питьевая вода'],
  },
  {
    canonicalName: 'чай чёрный',
    category: 'BEVERAGE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['черный чай'],
  },
  {
    canonicalName: 'чай зелёный',
    category: 'BEVERAGE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['зеленый чай'],
  },
  {
    canonicalName: 'чай травяной',
    category: 'BEVERAGE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['травяной чай'],
  },
  {
    canonicalName: 'кофе молотый',
    category: 'BEVERAGE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['молотый кофе', 'кофе'],
  },
  {
    canonicalName: 'кофе растворимый',
    category: 'BEVERAGE',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 35000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['растворимый кофе'],
  },
  {
    canonicalName: 'какао-порошок',
    category: 'BEVERAGE',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['какао'],
  },
  {
    canonicalName: 'какао-масло',
    category: 'BEVERAGE',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.9,
    ediblePartRatio: 1.0,
    aliases: ['масло какао'],
  },
  {
    canonicalName: 'сок яблочный',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 1000,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['яблочный сок'],
  },
  {
    canonicalName: 'сок апельсиновый',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 1000,
    avgPriceKopecks: 14000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.04,
    ediblePartRatio: 1.0,
    aliases: ['апельсиновый сок'],
  },
  {
    canonicalName: 'сок томатный',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 1000,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['томатный сок'],
  },
  {
    canonicalName: 'лимонад',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 7,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'квас',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 180,
    density: 1.02,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'компот',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 6000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: 7,
    defaultShelfDaysFreezer: 365,
    density: 1.04,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'морс',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 3,
    defaultShelfDaysPantry: 14,
    defaultShelfDaysFreezer: 365,
    density: 1.04,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'минеральная вода',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 730,
    density: 1.0,
    ediblePartRatio: 1.0,
    aliases: ['минералка'],
  },
  {
    canonicalName: 'газированная вода',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 5000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 365,
    density: 1.0,
    ediblePartRatio: 1.0,
    aliases: ['газировка'],
  },
  {
    canonicalName: 'тоник',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 365,
    density: 1.04,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'пиво светлое',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 1.01,
    ediblePartRatio: 1.0,
    aliases: ['светлое пиво', 'пиво'],
  },
  {
    canonicalName: 'пиво тёмное',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 1.01,
    ediblePartRatio: 1.0,
    aliases: ['темное пиво'],
  },
  {
    canonicalName: 'вино красное',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 750,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 3650,
    defaultShelfDaysFreezer: 3650,
    density: 0.99,
    ediblePartRatio: 1.0,
    aliases: ['красное вино', 'вино'],
  },
  {
    canonicalName: 'вино белое',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 750,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 3650,
    defaultShelfDaysFreezer: 3650,
    density: 0.99,
    ediblePartRatio: 1.0,
    aliases: ['белое вино'],
  },
  {
    canonicalName: 'шампанское',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 750,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 3650,
    defaultShelfDaysFreezer: 3650,
    density: 0.99,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'коньяк',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 80000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 36500,
    defaultShelfDaysFreezer: 36500,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'водка',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 40000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 36500,
    defaultShelfDaysFreezer: 36500,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'виски',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 80000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 36500,
    defaultShelfDaysFreezer: 36500,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: ['whisky'],
  },
  {
    canonicalName: 'ром',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 80000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 36500,
    defaultShelfDaysFreezer: 36500,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'текила',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 80000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 36500,
    defaultShelfDaysFreezer: 36500,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'джин',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 80000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 36500,
    defaultShelfDaysFreezer: 36500,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: ['gin'],
  },
  {
    canonicalName: 'ликёр',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 60000,
    defaultShelfDaysFridge: null,
    defaultShelfDaysPantry: 36500,
    defaultShelfDaysFreezer: 36500,
    density: 0.95,
    ediblePartRatio: 1.0,
    aliases: ['ликер'],
  },
  {
    canonicalName: 'сидр',
    category: 'BEVERAGE',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.01,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'сахар',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 1000,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 1825,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.85,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'мёд',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 1825,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 1.42,
    ediblePartRatio: 1.0,
    aliases: ['мед'],
  },
  {
    canonicalName: 'варенье',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'джем',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'шоколад чёрный',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: ['горький шоколад', 'черный шоколад'],
  },
  {
    canonicalName: 'шоколад молочный',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: ['молочный шоколад'],
  },
  {
    canonicalName: 'шоколад белый',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: ['белый шоколад'],
  },
  {
    canonicalName: 'конфеты',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'орехи грецкие',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 45000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.5,
    ediblePartRatio: 0.5,
    aliases: ['грецкий орех', 'грецкие орехи'],
  },
  {
    canonicalName: 'миндаль',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 60000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.5,
    ediblePartRatio: 0.5,
    aliases: [],
  },
  {
    canonicalName: 'кешью',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 60000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.5,
    ediblePartRatio: 0.5,
    aliases: [],
  },
  {
    canonicalName: 'фундук',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 50000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.5,
    ediblePartRatio: 0.5,
    aliases: [],
  },
  {
    canonicalName: 'арахис',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.5,
    ediblePartRatio: 0.7,
    aliases: [],
  },
  {
    canonicalName: 'фисташки',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 80000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.5,
    ediblePartRatio: 0.5,
    aliases: [],
  },
  {
    canonicalName: 'кунжут',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 0.6,
    ediblePartRatio: 0.9,
    aliases: ['семена кунжута'],
  },
  {
    canonicalName: 'мак',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 0.6,
    ediblePartRatio: 0.95,
    aliases: ['мак пищевой'],
  },
  {
    canonicalName: 'кокосовая стружка',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: ['кокос'],
  },
  {
    canonicalName: 'желатин',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 1825,
    defaultShelfDaysPantry: 3650,
    defaultShelfDaysFreezer: 3650,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'дрожжи',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 100,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 730,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: ['сухие дрожжи', 'прессованные дрожжи'],
  },
  {
    canonicalName: 'разрыхлитель',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.5,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'сода',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 1825,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 1.1,
    ediblePartRatio: 1.0,
    aliases: ['пищевая сода'],
  },
  {
    canonicalName: 'уксус столовый',
    category: 'OTHER',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 6000,
    defaultShelfDaysFridge: 1825,
    defaultShelfDaysPantry: 3650,
    defaultShelfDaysFreezer: 3650,
    density: 1.01,
    ediblePartRatio: 1.0,
    aliases: ['столовый уксус', 'уксус 9%'],
  },
  {
    canonicalName: 'уксус яблочный',
    category: 'OTHER',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 3650,
    defaultShelfDaysFreezer: 3650,
    density: 1.01,
    ediblePartRatio: 1.0,
    aliases: ['яблочный уксус'],
  },
  {
    canonicalName: 'уксус бальзамический',
    category: 'OTHER',
    defaultUnit: 'ML',
    packageSize: 250,
    avgPriceKopecks: 35000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 3650,
    defaultShelfDaysFreezer: 3650,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['бальзамический уксус', 'бальзамик'],
  },
  {
    canonicalName: 'соевый соус',
    category: 'OTHER',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 1.1,
    ediblePartRatio: 1.0,
    aliases: ['соевый соус', 'соя'],
  },
  {
    canonicalName: 'кетчуп',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 1.1,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'майонез',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 90,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 1.0,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'горчица столовая',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['столовая горчица'],
  },
  {
    canonicalName: 'томатная паста',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 1.1,
    ediblePartRatio: 1.0,
    aliases: ['томат-паста'],
  },
  {
    canonicalName: 'оливки',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'маслины',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: [],
  },
  {
    canonicalName: 'каперсы',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 200,
    avgPriceKopecks: 35000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.95,
    ediblePartRatio: 0.95,
    aliases: ['каперс'],
  },
  {
    canonicalName: 'кукурузный крахмал',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 730,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 0.6,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'томатный соус',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 10000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 1.1,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'рыбный соус',
    category: 'OTHER',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 1.1,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'соус терияки',
    category: 'OTHER',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 20000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 1.1,
    ediblePartRatio: 1.0,
    aliases: ['терияки'],
  },
  {
    canonicalName: 'соус чили',
    category: 'OTHER',
    defaultUnit: 'ML',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 1825,
    defaultShelfDaysFreezer: 1825,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: ['острый соус чили'],
  },
  {
    canonicalName: 'арахисовая паста',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 30000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.1,
    ediblePartRatio: 1.0,
    aliases: ['peanut butter', 'арахисовое масло'],
  },
  {
    canonicalName: 'тахини',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.0,
    ediblePartRatio: 1.0,
    aliases: ['кунжутная паста'],
  },
  {
    canonicalName: 'зефир',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 14,
    defaultShelfDaysPantry: 90,
    defaultShelfDaysFreezer: 180,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'мармелад',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'пастила',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 30,
    defaultShelfDaysPantry: 180,
    defaultShelfDaysFreezer: 365,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'цукаты',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 20000,
    defaultShelfDaysFridge: 90,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: ['цукат'],
  },
  {
    canonicalName: 'сухофрукты',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.95,
    ediblePartRatio: 0.85,
    aliases: ['смесь сухофруктов'],
  },
  {
    canonicalName: 'семена льна',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 365,
    defaultShelfDaysPantry: 730,
    defaultShelfDaysFreezer: 1095,
    density: 0.6,
    ediblePartRatio: 1.0,
    aliases: ['лён', 'льняное семя'],
  },
  {
    canonicalName: 'семена чиа',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 25000,
    defaultShelfDaysFridge: 1825,
    defaultShelfDaysPantry: 3650,
    defaultShelfDaysFreezer: 3650,
    density: 0.6,
    ediblePartRatio: 1.0,
    aliases: ['чиа'],
  },
  {
    canonicalName: 'тыквенные семечки',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 20000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.5,
    ediblePartRatio: 0.85,
    aliases: ['тыквенное семя'],
  },
  {
    canonicalName: 'подсолнечные семечки',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.5,
    ediblePartRatio: 0.85,
    aliases: ['подсолнечное семя'],
  },
  {
    canonicalName: 'попкорн',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 12000,
    defaultShelfDaysFridge: 180,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 0.4,
    ediblePartRatio: 1.0,
    aliases: ['кукуруза воздушная'],
  },
  {
    canonicalName: 'изомальт',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 15000,
    defaultShelfDaysFridge: 1825,
    defaultShelfDaysPantry: 3650,
    defaultShelfDaysFreezer: 3650,
    density: 1.05,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'глазурь шоколадная',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 18000,
    defaultShelfDaysFridge: 90,
    defaultShelfDaysPantry: 365,
    defaultShelfDaysFreezer: 730,
    density: 1.3,
    ediblePartRatio: 1.0,
    aliases: [],
  },
  {
    canonicalName: 'краситель пищевой',
    category: 'OTHER',
    defaultUnit: 'G',
    packageSize: 500,
    avgPriceKopecks: 8000,
    defaultShelfDaysFridge: 1825,
    defaultShelfDaysPantry: 3650,
    defaultShelfDaysFreezer: 3650,
    density: 1.0,
    ediblePartRatio: 1.0,
    aliases: ['пищевой краситель'],
  },
] as const;
