// MC-051 — MealPlans controller: POST /api/v1/meal-plans.
//
// 202 Accepted with { jobId, deduplicated }: the plan is generated by
// the worker; the client polls GET /jobs/:id (progress stages) and
// then reads the ACTIVE plan.

import { Body, Controller, Get, HttpCode, Inject, Post, Req, UseGuards } from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import type { FastifyRequest } from 'fastify';
import type { CreateMealPlanResponseDto, MealPlanSetupDto } from '@multichef/contracts';
import { AppHttpException } from '../common/exception-filter.js';
import { AuthGuard, currentUser } from '../common/auth-guard.js';
import type { AuthenticatedUser } from '../auth/auth.service.js';
import { MealPlanSetupDtoSchema } from './meal-plans.dto.js';
import { MealPlansService } from './meal-plans.service.js';

@ApiTags('meal-plans')
@UseGuards(AuthGuard)
@Controller({ path: 'meal-plans' })
export class MealPlansController {
  constructor(@Inject(MealPlansService) private readonly svc: MealPlansService) {}

  @Post()
  @HttpCode(202)
  @ApiOperation({ summary: 'Queue a weekly plan generation job' })
  @ApiResponse({ status: 202, description: 'Job recorded and enqueued' })
  @ApiResponse({ status: 401, description: 'No session' })
  async create(
    @Req() req: FastifyRequest,
    @Body() body: unknown,
  ): Promise<CreateMealPlanResponseDto> {
    const user = currentUser(req as unknown as { user: AuthenticatedUser });
    const parsed = MealPlanSetupDtoSchema.safeParse(body ?? {});
    if (!parsed.success) {
      const fields: Record<string, string[]> = {};
      for (const issue of parsed.error.issues) {
        const key = issue.path.join('.') || '_root';
        (fields[key] ??= []).push(issue.message);
      }
      throw new AppHttpException({
        code: 'VALIDATION_ERROR',
        message: 'Invalid request body',
        details: { fields },
      });
    }
    return this.svc.create(user.id, parsed.data);
  }

  @Get('active')
  @ApiOperation({ summary: 'The household’s ACTIVE weekly plan' })
  @ApiResponse({ status: 200, description: 'Plan with days and entries (null when none)' })
  async active(@Req() req: FastifyRequest): Promise<unknown> {
    const user = currentUser(req as unknown as { user: AuthenticatedUser });
    return this.svc.getActiveForUser(user.id);
  }
}
