// MC-051 — MealPlans controller: POST /api/v1/meal-plans.
//
// 202 Accepted with { jobId, deduplicated }: the plan is generated by
// the worker; the client polls GET /jobs/:id (progress stages) and
// then reads the ACTIVE plan.

import {
  Body,
  Controller,
  Get,
  HttpCode,
  Inject,
  Param,
  Patch,
  Post,
  Req,
  UseGuards,
} from '@nestjs/common';
import {
  ApiOperation,
  ApiResponse,
  ApiTags,
  ApiUnauthorizedResponse,
  ApiForbiddenResponse,
  ApiNotFoundResponse,
  ApiUnprocessableEntityResponse,
  ApiTooManyRequestsResponse,
  ApiInternalServerErrorResponse,
} from '@nestjs/swagger';
import type { FastifyRequest } from 'fastify';
import type {
  CreateMealPlanResponseDto,
  PrepSessionDto,
  StoragePlanDto,
} from '@multichef/contracts';
import { AppHttpException } from '../common/exception-filter.js';
import { AuthGuard, currentUser } from '../common/auth-guard.js';
import type { AuthenticatedUser } from '../auth/auth.service.js';
import { MealPlanSetupDtoSchema } from './meal-plans.dto.js';
import { MealPlansService } from './meal-plans.service.js';

@ApiTags('meal-plans')
@UseGuards(AuthGuard)
// Class-level error contract (E15/T34-B): applies to all routes.
@ApiUnauthorizedResponse({ description: 'No/expired session' })
@ApiForbiddenResponse({ description: 'No rights for the resource' })
@ApiNotFoundResponse({ description: 'Resource not found' })
@ApiUnprocessableEntityResponse({ description: 'Domain constraint' })
@ApiTooManyRequestsResponse({ description: 'Rate limit' })
@ApiInternalServerErrorResponse({ description: 'Internal error' })
@Controller({ path: 'meal-plans' })
export class MealPlansController {
  constructor(@Inject(MealPlansService) private readonly svc: MealPlansService) {}

  @Post()
  @HttpCode(202)
  @ApiOperation({ summary: 'Queue a weekly plan generation job' })
  @ApiResponse({ status: 202, description: 'Job recorded and enqueued' })
  @ApiResponse({ status: 401, description: 'No session' })
  async create(
    @Req() req: FastifyRequest,
    // eslint-disable-next-line multichef/require-zod-body-schema -- body is intentionally `unknown`; service uses ad-hoc validation via internal contract
    @Body() body: unknown,
  ): Promise<CreateMealPlanResponseDto> {
    const user = currentUser(req as unknown as { user: AuthenticatedUser });
    const parsed = MealPlanSetupDtoSchema.safeParse(body ?? {});
    if (!parsed.success) {
      const fields: Record<string, string[]> = {};
      for (const issue of parsed.error.issues) {
        const key = issue.path.join('.') || '_root';
        (fields[key] ??= []).push(issue.message);
      }
      throw new AppHttpException({
        code: 'VALIDATION_ERROR',
        message: 'Invalid request body',
        details: { fields },
      });
    }
    return this.svc.create(user.id, parsed.data);
  }

  @Get('active')
  @ApiOperation({ summary: 'The household’s ACTIVE weekly plan' })
  @ApiResponse({ status: 200, description: 'Plan with days and entries (null when none)' })
  async active(@Req() req: FastifyRequest): Promise<unknown> {
    const user = currentUser(req as unknown as { user: AuthenticatedUser });
    return this.svc.getActiveForUser(user.id);
  }

  /** MC-060: generate (idempotent) the prep session for the ACTIVE plan. */
  @Post('active/prep')
  @HttpCode(200)
  @ApiOperation({ summary: 'Build the prep-session task list for the active plan' })
  async prep(@Req() req: FastifyRequest): Promise<PrepSessionDto> {
    const user = currentUser(req as unknown as { user: AuthenticatedUser });
    return this.svc.generatePrepSession(user.id, 'BATCH_3H');
  }

  /** MC-060: toggle a prep task done flag. */
  @Patch('prep-tasks/:taskId')
  @HttpCode(200)
  @ApiOperation({ summary: 'Toggle a prep task done flag' })
  async toggleTask(
    @Req() req: FastifyRequest,
    @Param('taskId') taskId: string,
    // eslint-disable-next-line multichef/require-zod-body-schema -- body is intentionally `unknown`; service uses ad-hoc validation via internal contract
    @Body() body: unknown,
  ): Promise<{ done: boolean }> {
    const user = currentUser(req as unknown as { user: AuthenticatedUser });
    const done = (body as { done?: unknown } | null)?.done === true;
    return this.svc.togglePrepTask(user.id, taskId, done);
  }

  /** MC-061: containers + defrost calendar for the ACTIVE plan. */
  @Get('active/storage')
  @ApiOperation({ summary: 'Storage plan: containers and the defrost calendar' })
  async storage(@Req() req: FastifyRequest): Promise<StoragePlanDto> {
    const user = currentUser(req as unknown as { user: AuthenticatedUser });
    return this.svc.getStoragePlan(user.id);
  }
}
