// MC-INGREDIENT-NUTRITION — catalog name -> nutrition key mapping.
//
// Every distinct Ingredient.canonicalName used by the MC-031 recipe seed
// MUST have an entry here; anything missing lands in the seed runner's
// `unresolved` list (visible warning, never a silent skip).

export const CATALOG_TO_NUTRITION: Record<string, string> = {
  авокадо: 'avokado',
  аджика: 'adzhika',
  айва: 'ayva',
  ананас: 'ananas',
  апельсин: 'apelsin',
  арахис: 'arahis',
  'арахисовая паста': 'arahisovaya-pasta',
  арбуз: 'arbuz',
  багет: 'baget',
  базилик: 'bazilik',
  'базилик сушёный': 'bazilik-sushenyy',
  баклажан: 'baklazhan',
  банан: 'banan',
  баранина: 'baranina',
  батат: 'batat',
  батон: 'baton',
  бекон: 'bekon',
  брокколи: 'brokkoli',
  брусника: 'brusnika',
  булгур: 'bulgur',
  ваниль: 'vanil',
  варенье: 'varene',
  ветчина: 'vetchina',
  'вино белое': 'vino-beloe',
  'вино красное': 'vino-krasnoe',
  виноград: 'vinograd',
  вишня: 'vishnya',
  вода: 'voda',
  гвоздика: 'gvozdika',
  'глазурь шоколадная': 'glazur-shokoladnaya',
  'говядина (вырезка)': 'govyadina-vyrezka',
  'говядина (лопатка)': 'govyadina-lopatka',
  'говядина (фарш)': 'govyadina-farsh',
  голубика: 'golubika',
  'горошек зелёный': 'goroshek-zelenyy',
  горчица: 'gorchitsa',
  'горчица столовая': 'gorchitsa-stolovaya',
  гранат: 'granat',
  гранола: 'granola',
  гречка: 'grechka',
  груша: 'grusha',
  гусь: 'gus',
  джем: 'dzhem',
  дрожжи: 'drozhzhi',
  дыня: 'dynya',
  желатин: 'zhelatin',
  зефир: 'zefir',
  изомальт: 'izomalt',
  изюм: 'izyum',
  имбирь: 'imbir',
  'индейка (бедро)': 'indeyka-bedro',
  'индейка (грудка)': 'indeyka-grudka',
  инжир: 'inzhir',
  'йогурт греческий': 'yogurt-grecheskiy',
  'йогурт натуральный': 'yogurt-naturalnyy',
  кабачок: 'kabachok',
  'какао-порошок': 'kakao-poroshok',
  каперсы: 'kapersy',
  'капуста белокочанная': 'kapusta-belokochannaya',
  'капуста цветная': 'kapusta-tsvetnaya',
  кардамон: 'kardamon',
  карри: 'karri',
  картофель: 'kartofel',
  квас: 'kvas',
  кетчуп: 'ketchup',
  'кефир 1%': 'kefir-1',
  'кефир 3,2%': 'kefir-32',
  'кефир обезжиренный': 'kefir-obezzhirennyy',
  кешью: 'keshyu',
  киви: 'kivi',
  киноа: 'kinoa',
  клубника: 'klubnika',
  клюква: 'klyukva',
  'кокосовая стружка': 'kokosovaya-struzhka',
  'колбаса вареная': 'kolbasa-varenaya',
  'колбаса копчёная': 'kolbasa-kopchenaya',
  компот: 'kompot',
  конфеты: 'konfety',
  'кориандр молотый': 'koriandr-molotyy',
  корица: 'koritsa',
  котлеты: 'kotlety',
  'кофе молотый': 'kofe-molotyy',
  'кофе растворимый': 'kofe-rastvorimyy',
  'краситель пищевой': 'krasitel-pischevoy',
  'крахмал картофельный': 'krahmal-kartofelnyy',
  крекер: 'kreker',
  кролик: 'krolik',
  круассан: 'kruassan',
  крыжовник: 'kryzhovnik',
  кукуруза: 'kukuruza',
  'кукурузные хлопья': 'kukuruznye-hlopya',
  кумин: 'kumin',
  кунжут: 'kunzhut',
  курага: 'kuraga',
  'куриные бёдра': 'kurinye-bedra',
  'куриные крылышки': 'kurinye-krylyshki',
  'курица (бедро)': 'kuritsa-bedro',
  'курица (грудка)': 'kuritsa-grudka',
  куркума: 'kurkuma',
  кускус: 'kuskus',
  'лавровый лист': 'lavrovyy-list',
  лайм: 'laym',
  'лапша рисовая': 'lapsha-risovaya',
  'лапша удон': 'lapsha-udon',
  'лапша яичная': 'lapsha-yaichnaya',
  лед: 'led',
  лимон: 'limon',
  лимонад: 'limonad',
  'лук красный': 'luk-krasnyy',
  'лук репчатый': 'luk-repchatyy',
  'лук-порей': 'luk-porey',
  майонез: 'mayonez',
  майоран: 'mayoran',
  мак: 'mak',
  макароны: 'makarony',
  малина: 'malina',
  манго: 'mango',
  маргарин: 'margarin',
  мармелад: 'marmelad',
  маслины: 'masliny',
  'масло сливочное': 'maslo-slivochnoe',
  миндаль: 'mindal',
  'минеральная вода': 'mineralnaya-voda',
  'молоко (козье)': 'moloko-koze',
  'молоко (коровье)': 'moloko-korove',
  'молоко (овсяное)': 'moloko-ovsyanoe',
  морковь: 'morkov',
  мороженое: 'morozhenoe',
  морс: 'mors',
  'мука кукурузная': 'muka-kukuruznaya',
  'мука пшеничная': 'muka-pshenichnaya',
  'мука ржаная': 'muka-rzhanaya',
  'мускатный орех': 'muskatnyy-oreh',
  мюсли: 'myusli',
  'мята сушёная': 'myata-sushenaya',
  мёд: 'med',
  облепиха: 'oblepiha',
  овсянка: 'ovsyanka',
  огурец: 'ogurets',
  оливки: 'olivki',
  орегано: 'oregano',
  'орехи грецкие': 'orehi-gretskie',
  паприка: 'paprika',
  пастила: 'pastila',
  пельмени: 'pelmeni',
  пенне: 'penne',
  'перец болгарский': 'perets-bolgarskiy',
  'перец красный': 'perets-krasnyy',
  'перец чили': 'perets-chili',
  'перец чёрный': 'perets-chernyy',
  перловка: 'perlovka',
  петрушка: 'petrushka',
  'печень говяжья': 'pechen-govyazhya',
  печенье: 'pechene',
  'подсолнечные семечки': 'podsolnechnye-semechki',
  помидор: 'pomidor',
  'помидоры черри': 'pomidory-cherri',
  попкорн: 'popkorn',
  простокваша: 'prostokvasha',
  пшено: 'psheno',
  разрыхлитель: 'razryhlitel',
  редис: 'redis',
  'рис басмати': 'ris-basmati',
  'рис белый': 'ris-belyy',
  'рис бурый': 'ris-buryy',
  розмарин: 'rozmarin',
  руккола: 'rukkola',
  'рыбный соус': 'rybnyy-sous',
  ряженка: 'ryazhenka',
  'салат айсберг': 'salat-aysberg',
  сахар: 'sahar',
  'свинина (вырезка)': 'svinina-vyrezka',
  'свинина (фарш)': 'svinina-farsh',
  свёкла: 'svekla',
  сгущёнка: 'sguschenka',
  сельдерей: 'selderey',
  'семена льна': 'semena-lna',
  'семена чиа': 'semena-chia',
  'сердце говяжье': 'serdtse-govyazhe',
  'сливки 10%': 'slivki-10',
  'сливки 20%': 'slivki-20',
  'сливки 33%': 'slivki-33',
  'сметана 15%': 'smetana-15',
  'сметана 20%': 'smetana-20',
  'сметана 25%': 'smetana-25',
  'смородина чёрная': 'smorodina-chernaya',
  сода: 'soda',
  'соевый соус': 'soevyy-sous',
  'сок апельсиновый': 'sok-apelsinovyy',
  'сок томатный': 'sok-tomatnyy',
  'сок яблочный': 'sok-yablochnyy',
  соль: 'sol',
  сосиски: 'sosiski',
  'соус терияки': 'sous-teriyaki',
  'соус чили': 'sous-chili',
  спагетти: 'spagetti',
  'сухари панировочные': 'suhari-panirovochnye',
  сухофрукты: 'suhofrukty',
  сушки: 'sushki',
  'сыр Бри': 'syr-bri',
  'сыр Гауда': 'syr-gauda',
  'сыр Дор Блю': 'syr-dor-blyu',
  'сыр Маскарпоне': 'syr-maskarpone',
  'сыр Моцарелла': 'syr-motsarella',
  'сыр Пармезан': 'syr-parmezan',
  'сыр Рикотта': 'syr-rikotta',
  'сыр Российский': 'syr-rossiyskiy',
  'сыр Фета': 'syr-feta',
  'сыр Чеддер': 'syr-chedder',
  тахини: 'tahini',
  творог: 'tvorog',
  'творог 5%': 'tvorog-5',
  'творог 9%': 'tvorog-9',
  'творог обезжиренный': 'tvorog-obezzhirennyy',
  телятина: 'telyatina',
  тимьян: 'timyan',
  тмин: 'tmin',
  толокно: 'tolokno',
  'томатная паста': 'tomatnaya-pasta',
  'томатный соус': 'tomatnyy-sous',
  тыква: 'tykva',
  'тыквенные семечки': 'tykvennye-semechki',
  укроп: 'ukrop',
  'уксус бальзамический': 'uksus-balzamicheskiy',
  'уксус столовый': 'uksus-stolovyy',
  'уксус яблочный': 'uksus-yablochnyy',
  утка: 'utka',
  'фарш говяжий': 'farsh-govyazhiy',
  'фарш индейки': 'farsh-indeyki',
  'фарш куриный': 'farsh-kurinyy',
  'фарш свиной': 'farsh-svinoy',
  'фасоль стручковая': 'fasol-struchkovaya',
  фейхоа: 'feyhoa',
  финики: 'finiki',
  фисташки: 'fistashki',
  фузилли: 'fuzilli',
  фундук: 'funduk',
  'хлеб белый': 'hleb-belyy',
  'хлеб чёрный': 'hleb-chernyy',
  'хмели-сунели': 'hmeli-suneli',
  хурма: 'hurma',
  цукаты: 'tsukaty',
  'чай зелёный': 'chay-zelenyy',
  'чай травяной': 'chay-travyanoy',
  'чай чёрный': 'chay-chernyy',
  черешня: 'chereshnya',
  черника: 'chernika',
  чеснок: 'chesnok',
  шафран: 'shafran',
  шиповник: 'shipovnik',
  'шоколад белый': 'shokolad-belyy',
  'шоколад молочный': 'shokolad-molochnyy',
  'шоколад чёрный': 'shokolad-chernyy',
  шпинат: 'shpinat',
  щавель: 'schavel',
  эстрагон: 'estragon',
  яблоко: 'yabloko',
  язык: 'yazyk',
  'яйцо куриное': 'yaytso-kurinoe',
  'яйцо перепелиное': 'yaytso-perepelinoe',
};
