// MC-INGREDIENT-NUTRITION — per-100g nutrition table for seeded ingredients.
//
// Values come from the MC-031 generation table (USDA / Химсостав approximations)
// and cover every distinct ingredient used by the 269 seeded recipes.
// Keys are ASCII slugs derived from the Russian canonical name (catalog-mapping.ts
// maps catalog name -> key). Zero values are real: salt/water/spices have no
// meaningful kcal at 100 g doses.

export type NutritionEntry = {
  key: string;
  servingSizeG: 100;
  servingCalories: number;
  servingProteinG: number;
  servingFatG: number;
  servingCarbsG: number;
  source: 'USDA' | 'OFFICIAL' | 'INTERNAL';
  sourceUpdatedAt: string; // ISO date
};

export const NUTRITION_TABLE: Record<string, NutritionEntry> = {
  adzhika: {
    key: 'adzhika',
    servingSizeG: 100,
    servingCalories: 59,
    servingProteinG: 1.5,
    servingFatG: 2.5,
    servingCarbsG: 8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  ananas: {
    key: 'ananas',
    servingSizeG: 100,
    servingCalories: 52,
    servingProteinG: 0.4,
    servingFatG: 0.2,
    servingCarbsG: 11.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  apelsin: {
    key: 'apelsin',
    servingSizeG: 100,
    servingCalories: 43,
    servingProteinG: 0.9,
    servingFatG: 0.2,
    servingCarbsG: 8.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  arahis: {
    key: 'arahis',
    servingSizeG: 100,
    servingCalories: 567,
    servingProteinG: 25.8,
    servingFatG: 49.2,
    servingCarbsG: 16.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'arahisovaya-pasta': {
    key: 'arahisovaya-pasta',
    servingSizeG: 100,
    servingCalories: 588,
    servingProteinG: 25.1,
    servingFatG: 50.4,
    servingCarbsG: 19.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  arbuz: {
    key: 'arbuz',
    servingSizeG: 100,
    servingCalories: 30,
    servingProteinG: 0.6,
    servingFatG: 0.2,
    servingCarbsG: 7.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  avokado: {
    key: 'avokado',
    servingSizeG: 100,
    servingCalories: 160,
    servingProteinG: 2,
    servingFatG: 14.7,
    servingCarbsG: 8.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  ayva: {
    key: 'ayva',
    servingSizeG: 100,
    servingCalories: 57,
    servingProteinG: 0.4,
    servingFatG: 0.1,
    servingCarbsG: 15.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  baget: {
    key: 'baget',
    servingSizeG: 100,
    servingCalories: 274,
    servingProteinG: 8.8,
    servingFatG: 2.5,
    servingCarbsG: 54,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  baklazhan: {
    key: 'baklazhan',
    servingSizeG: 100,
    servingCalories: 24,
    servingProteinG: 1.2,
    servingFatG: 0.1,
    servingCarbsG: 5.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  banan: {
    key: 'banan',
    servingSizeG: 100,
    servingCalories: 96,
    servingProteinG: 1.5,
    servingFatG: 0.2,
    servingCarbsG: 21,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  baranina: {
    key: 'baranina',
    servingSizeG: 100,
    servingCalories: 209,
    servingProteinG: 16.3,
    servingFatG: 15.7,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  batat: {
    key: 'batat',
    servingSizeG: 100,
    servingCalories: 86,
    servingProteinG: 1.6,
    servingFatG: 0.1,
    servingCarbsG: 20,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  baton: {
    key: 'baton',
    servingSizeG: 100,
    servingCalories: 262,
    servingProteinG: 9.2,
    servingFatG: 2.9,
    servingCarbsG: 51,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  bazilik: {
    key: 'bazilik',
    servingSizeG: 100,
    servingCalories: 27,
    servingProteinG: 3.2,
    servingFatG: 0.6,
    servingCarbsG: 1.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'bazilik-sushenyy': {
    key: 'bazilik-sushenyy',
    servingSizeG: 100,
    servingCalories: 233,
    servingProteinG: 22.8,
    servingFatG: 4,
    servingCarbsG: 47.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  bekon: {
    key: 'bekon',
    servingSizeG: 100,
    servingCalories: 500,
    servingProteinG: 37,
    servingFatG: 45,
    servingCarbsG: 1.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  brokkoli: {
    key: 'brokkoli',
    servingSizeG: 100,
    servingCalories: 34,
    servingProteinG: 2.8,
    servingFatG: 0.4,
    servingCarbsG: 7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  brusnika: {
    key: 'brusnika',
    servingSizeG: 100,
    servingCalories: 46,
    servingProteinG: 0.7,
    servingFatG: 0.7,
    servingCarbsG: 9.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  bulgur: {
    key: 'bulgur',
    servingSizeG: 100,
    servingCalories: 342,
    servingProteinG: 12.3,
    servingFatG: 1.3,
    servingCarbsG: 75.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'chay-chernyy': {
    key: 'chay-chernyy',
    servingSizeG: 100,
    servingCalories: 140,
    servingProteinG: 20,
    servingFatG: 0.5,
    servingCarbsG: 4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'chay-travyanoy': {
    key: 'chay-travyanoy',
    servingSizeG: 100,
    servingCalories: 5,
    servingProteinG: 0.2,
    servingFatG: 0,
    servingCarbsG: 1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'chay-zelenyy': {
    key: 'chay-zelenyy',
    servingSizeG: 100,
    servingCalories: 1,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 0.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  chereshnya: {
    key: 'chereshnya',
    servingSizeG: 100,
    servingCalories: 50,
    servingProteinG: 1.1,
    servingFatG: 0.4,
    servingCarbsG: 10.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  chernika: {
    key: 'chernika',
    servingSizeG: 100,
    servingCalories: 57,
    servingProteinG: 0.7,
    servingFatG: 0.3,
    servingCarbsG: 14.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  chesnok: {
    key: 'chesnok',
    servingSizeG: 100,
    servingCalories: 149,
    servingProteinG: 6.4,
    servingFatG: 0.5,
    servingCarbsG: 30,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  drozhzhi: {
    key: 'drozhzhi',
    servingSizeG: 100,
    servingCalories: 325,
    servingProteinG: 40.4,
    servingFatG: 7.6,
    servingCarbsG: 41.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  dynya: {
    key: 'dynya',
    servingSizeG: 100,
    servingCalories: 38,
    servingProteinG: 0.6,
    servingFatG: 0.2,
    servingCarbsG: 9.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  dzhem: {
    key: 'dzhem',
    servingSizeG: 100,
    servingCalories: 238,
    servingProteinG: 0.3,
    servingFatG: 0,
    servingCarbsG: 60,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  estragon: {
    key: 'estragon',
    servingSizeG: 100,
    servingCalories: 295,
    servingProteinG: 22.8,
    servingFatG: 7.2,
    servingCarbsG: 50.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'farsh-govyazhiy': {
    key: 'farsh-govyazhiy',
    servingSizeG: 100,
    servingCalories: 227,
    servingProteinG: 17.5,
    servingFatG: 17.5,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'farsh-indeyki': {
    key: 'farsh-indeyki',
    servingSizeG: 100,
    servingCalories: 161,
    servingProteinG: 19.7,
    servingFatG: 8.7,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'farsh-kurinyy': {
    key: 'farsh-kurinyy',
    servingSizeG: 100,
    servingCalories: 143,
    servingProteinG: 17.6,
    servingFatG: 8.1,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'farsh-svinoy': {
    key: 'farsh-svinoy',
    servingSizeG: 100,
    servingCalories: 263,
    servingProteinG: 16.9,
    servingFatG: 21.6,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'fasol-struchkovaya': {
    key: 'fasol-struchkovaya',
    servingSizeG: 100,
    servingCalories: 31,
    servingProteinG: 1.8,
    servingFatG: 0.1,
    servingCarbsG: 7.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  feyhoa: {
    key: 'feyhoa',
    servingSizeG: 100,
    servingCalories: 61,
    servingProteinG: 0.9,
    servingFatG: 0.4,
    servingCarbsG: 13,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  finiki: {
    key: 'finiki',
    servingSizeG: 100,
    servingCalories: 282,
    servingProteinG: 2.5,
    servingFatG: 0.4,
    servingCarbsG: 75,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  fistashki: {
    key: 'fistashki',
    servingSizeG: 100,
    servingCalories: 560,
    servingProteinG: 20.2,
    servingFatG: 50,
    servingCarbsG: 28.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  funduk: {
    key: 'funduk',
    servingSizeG: 100,
    servingCalories: 628,
    servingProteinG: 15,
    servingFatG: 60.8,
    servingCarbsG: 16.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  fuzilli: {
    key: 'fuzilli',
    servingSizeG: 100,
    servingCalories: 358,
    servingProteinG: 12.5,
    servingFatG: 1.5,
    servingCarbsG: 78.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'glazur-shokoladnaya': {
    key: 'glazur-shokoladnaya',
    servingSizeG: 100,
    servingCalories: 510,
    servingProteinG: 4.5,
    servingFatG: 30,
    servingCarbsG: 60,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  golubika: {
    key: 'golubika',
    servingSizeG: 100,
    servingCalories: 57,
    servingProteinG: 0.7,
    servingFatG: 0.3,
    servingCarbsG: 14.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  gorchitsa: {
    key: 'gorchitsa',
    servingSizeG: 100,
    servingCalories: 162,
    servingProteinG: 5.8,
    servingFatG: 7.3,
    servingCarbsG: 15.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'gorchitsa-stolovaya': {
    key: 'gorchitsa-stolovaya',
    servingSizeG: 100,
    servingCalories: 112,
    servingProteinG: 4.4,
    servingFatG: 5.4,
    servingCarbsG: 11.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'goroshek-zelenyy': {
    key: 'goroshek-zelenyy',
    servingSizeG: 100,
    servingCalories: 81,
    servingProteinG: 5.4,
    servingFatG: 0.4,
    servingCarbsG: 14.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'govyadina-farsh': {
    key: 'govyadina-farsh',
    servingSizeG: 100,
    servingCalories: 227,
    servingProteinG: 17.5,
    servingFatG: 17.5,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'govyadina-lopatka': {
    key: 'govyadina-lopatka',
    servingSizeG: 100,
    servingCalories: 193,
    servingProteinG: 19.4,
    servingFatG: 12.7,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'govyadina-vyrezka': {
    key: 'govyadina-vyrezka',
    servingSizeG: 100,
    servingCalories: 156,
    servingProteinG: 22.2,
    servingFatG: 7.1,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  granat: {
    key: 'granat',
    servingSizeG: 100,
    servingCalories: 83,
    servingProteinG: 1.7,
    servingFatG: 1.2,
    servingCarbsG: 18.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  granola: {
    key: 'granola',
    servingSizeG: 100,
    servingCalories: 460,
    servingProteinG: 10,
    servingFatG: 20,
    servingCarbsG: 60,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  grechka: {
    key: 'grechka',
    servingSizeG: 100,
    servingCalories: 313,
    servingProteinG: 12.6,
    servingFatG: 3.3,
    servingCarbsG: 62.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  grusha: {
    key: 'grusha',
    servingSizeG: 100,
    servingCalories: 57,
    servingProteinG: 0.4,
    servingFatG: 0.1,
    servingCarbsG: 15.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  gus: {
    key: 'gus',
    servingSizeG: 100,
    servingCalories: 328,
    servingProteinG: 25.7,
    servingFatG: 25.1,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  gvozdika: {
    key: 'gvozdika',
    servingSizeG: 100,
    servingCalories: 274,
    servingProteinG: 6.4,
    servingFatG: 13,
    servingCarbsG: 65.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'hleb-belyy': {
    key: 'hleb-belyy',
    servingSizeG: 100,
    servingCalories: 235,
    servingProteinG: 8,
    servingFatG: 3,
    servingCarbsG: 49,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'hleb-chernyy': {
    key: 'hleb-chernyy',
    servingSizeG: 100,
    servingCalories: 217,
    servingProteinG: 6.6,
    servingFatG: 1.2,
    servingCarbsG: 44,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'hmeli-suneli': {
    key: 'hmeli-suneli',
    servingSizeG: 100,
    servingCalories: 300,
    servingProteinG: 10,
    servingFatG: 8,
    servingCarbsG: 50,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  hurma: {
    key: 'hurma',
    servingSizeG: 100,
    servingCalories: 67,
    servingProteinG: 0.5,
    servingFatG: 0.4,
    servingCarbsG: 17.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  imbir: {
    key: 'imbir',
    servingSizeG: 100,
    servingCalories: 80,
    servingProteinG: 1.8,
    servingFatG: 0.8,
    servingCarbsG: 17.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'indeyka-bedro': {
    key: 'indeyka-bedro',
    servingSizeG: 100,
    servingCalories: 144,
    servingProteinG: 17,
    servingFatG: 7.1,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'indeyka-grudka': {
    key: 'indeyka-grudka',
    servingSizeG: 100,
    servingCalories: 104,
    servingProteinG: 19.2,
    servingFatG: 2.2,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  inzhir: {
    key: 'inzhir',
    servingSizeG: 100,
    servingCalories: 74,
    servingProteinG: 0.8,
    servingFatG: 0.3,
    servingCarbsG: 19.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  izomalt: {
    key: 'izomalt',
    servingSizeG: 100,
    servingCalories: 240,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 99,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  izyum: {
    key: 'izyum',
    servingSizeG: 100,
    servingCalories: 264,
    servingProteinG: 2.9,
    servingFatG: 0.6,
    servingCarbsG: 66,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kabachok: {
    key: 'kabachok',
    servingSizeG: 100,
    servingCalories: 24,
    servingProteinG: 0.6,
    servingFatG: 0.3,
    servingCarbsG: 5.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kakao-poroshok': {
    key: 'kakao-poroshok',
    servingSizeG: 100,
    servingCalories: 289,
    servingProteinG: 19.6,
    servingFatG: 13.7,
    servingCarbsG: 57.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kapersy: {
    key: 'kapersy',
    servingSizeG: 100,
    servingCalories: 23,
    servingProteinG: 2.4,
    servingFatG: 0.9,
    servingCarbsG: 4.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kapusta-belokochannaya': {
    key: 'kapusta-belokochannaya',
    servingSizeG: 100,
    servingCalories: 28,
    servingProteinG: 1.8,
    servingFatG: 0.1,
    servingCarbsG: 5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kapusta-tsvetnaya': {
    key: 'kapusta-tsvetnaya',
    servingSizeG: 100,
    servingCalories: 25,
    servingProteinG: 1.9,
    servingFatG: 0.3,
    servingCarbsG: 5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kardamon: {
    key: 'kardamon',
    servingSizeG: 100,
    servingCalories: 311,
    servingProteinG: 10.8,
    servingFatG: 6.7,
    servingCarbsG: 68.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  karri: {
    key: 'karri',
    servingSizeG: 100,
    servingCalories: 325,
    servingProteinG: 14.3,
    servingFatG: 14,
    servingCarbsG: 53.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kartofel: {
    key: 'kartofel',
    servingSizeG: 100,
    servingCalories: 77,
    servingProteinG: 2,
    servingFatG: 0.1,
    servingCarbsG: 17,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kefir-1': {
    key: 'kefir-1',
    servingSizeG: 100,
    servingCalories: 40,
    servingProteinG: 3,
    servingFatG: 1,
    servingCarbsG: 4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kefir-32': {
    key: 'kefir-32',
    servingSizeG: 100,
    servingCalories: 59,
    servingProteinG: 3.1,
    servingFatG: 3.2,
    servingCarbsG: 4.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kefir-obezzhirennyy': {
    key: 'kefir-obezzhirennyy',
    servingSizeG: 100,
    servingCalories: 30,
    servingProteinG: 3,
    servingFatG: 0.1,
    servingCarbsG: 3.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  keshyu: {
    key: 'keshyu',
    servingSizeG: 100,
    servingCalories: 553,
    servingProteinG: 18.2,
    servingFatG: 43.9,
    servingCarbsG: 30.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  ketchup: {
    key: 'ketchup',
    servingSizeG: 100,
    servingCalories: 93,
    servingProteinG: 1.3,
    servingFatG: 0.1,
    servingCarbsG: 22.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kinoa: {
    key: 'kinoa',
    servingSizeG: 100,
    servingCalories: 368,
    servingProteinG: 14.1,
    servingFatG: 6.1,
    servingCarbsG: 57.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kivi: {
    key: 'kivi',
    servingSizeG: 100,
    servingCalories: 61,
    servingProteinG: 1.1,
    servingFatG: 0.5,
    servingCarbsG: 14.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  klubnika: {
    key: 'klubnika',
    servingSizeG: 100,
    servingCalories: 33,
    servingProteinG: 0.7,
    servingFatG: 0.4,
    servingCarbsG: 7.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  klyukva: {
    key: 'klyukva',
    servingSizeG: 100,
    servingCalories: 46,
    servingProteinG: 0.4,
    servingFatG: 0.1,
    servingCarbsG: 12.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kofe-molotyy': {
    key: 'kofe-molotyy',
    servingSizeG: 100,
    servingCalories: 2,
    servingProteinG: 0.1,
    servingFatG: 0,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kofe-rastvorimyy': {
    key: 'kofe-rastvorimyy',
    servingSizeG: 100,
    servingCalories: 241,
    servingProteinG: 13,
    servingFatG: 0.5,
    servingCarbsG: 40,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kokosovaya-struzhka': {
    key: 'kokosovaya-struzhka',
    servingSizeG: 100,
    servingCalories: 660,
    servingProteinG: 6.9,
    servingFatG: 64.5,
    servingCarbsG: 23.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kolbasa-kopchenaya': {
    key: 'kolbasa-kopchenaya',
    servingSizeG: 100,
    servingCalories: 466,
    servingProteinG: 16.2,
    servingFatG: 44.6,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kolbasa-varenaya': {
    key: 'kolbasa-varenaya',
    servingSizeG: 100,
    servingCalories: 228,
    servingProteinG: 12.8,
    servingFatG: 20.1,
    servingCarbsG: 2.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kompot: {
    key: 'kompot',
    servingSizeG: 100,
    servingCalories: 85,
    servingProteinG: 0.2,
    servingFatG: 0,
    servingCarbsG: 22,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  konfety: {
    key: 'konfety',
    servingSizeG: 100,
    servingCalories: 400,
    servingProteinG: 4,
    servingFatG: 14,
    servingCarbsG: 65,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'koriandr-molotyy': {
    key: 'koriandr-molotyy',
    servingSizeG: 100,
    servingCalories: 298,
    servingProteinG: 12.4,
    servingFatG: 13.9,
    servingCarbsG: 55,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  koritsa: {
    key: 'koritsa',
    servingSizeG: 100,
    servingCalories: 247,
    servingProteinG: 4,
    servingFatG: 1.2,
    servingCarbsG: 80.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kotlety: {
    key: 'kotlety',
    servingSizeG: 100,
    servingCalories: 243,
    servingProteinG: 14.2,
    servingFatG: 17.5,
    servingCarbsG: 9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'krahmal-kartofelnyy': {
    key: 'krahmal-kartofelnyy',
    servingSizeG: 100,
    servingCalories: 313,
    servingProteinG: 0.1,
    servingFatG: 0.1,
    servingCarbsG: 83.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'krasitel-pischevoy': {
    key: 'krasitel-pischevoy',
    servingSizeG: 100,
    servingCalories: 0,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kreker: {
    key: 'kreker',
    servingSizeG: 100,
    servingCalories: 430,
    servingProteinG: 9,
    servingFatG: 11,
    servingCarbsG: 72,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  krolik: {
    key: 'krolik',
    servingSizeG: 100,
    servingCalories: 156,
    servingProteinG: 21.1,
    servingFatG: 8,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kruassan: {
    key: 'kruassan',
    servingSizeG: 100,
    servingCalories: 406,
    servingProteinG: 8.2,
    servingFatG: 21,
    servingCarbsG: 45.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kryzhovnik: {
    key: 'kryzhovnik',
    servingSizeG: 100,
    servingCalories: 45,
    servingProteinG: 0.9,
    servingFatG: 0.6,
    servingCarbsG: 9.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kukuruza: {
    key: 'kukuruza',
    servingSizeG: 100,
    servingCalories: 96,
    servingProteinG: 4,
    servingFatG: 1.5,
    servingCarbsG: 21,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kukuruznye-hlopya': {
    key: 'kukuruznye-hlopya',
    servingSizeG: 100,
    servingCalories: 357,
    servingProteinG: 7.5,
    servingFatG: 0.9,
    servingCarbsG: 83.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kumin: {
    key: 'kumin',
    servingSizeG: 100,
    servingCalories: 375,
    servingProteinG: 17.8,
    servingFatG: 22.3,
    servingCarbsG: 44.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kunzhut: {
    key: 'kunzhut',
    servingSizeG: 100,
    servingCalories: 573,
    servingProteinG: 17.7,
    servingFatG: 49.7,
    servingCarbsG: 23.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kuraga: {
    key: 'kuraga',
    servingSizeG: 100,
    servingCalories: 232,
    servingProteinG: 5.2,
    servingFatG: 0.5,
    servingCarbsG: 51,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kurinye-bedra': {
    key: 'kurinye-bedra',
    servingSizeG: 100,
    servingCalories: 158,
    servingProteinG: 20.8,
    servingFatG: 8.2,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kurinye-krylyshki': {
    key: 'kurinye-krylyshki',
    servingSizeG: 100,
    servingCalories: 186,
    servingProteinG: 19.7,
    servingFatG: 11.7,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kuritsa-bedro': {
    key: 'kuritsa-bedro',
    servingSizeG: 100,
    servingCalories: 158,
    servingProteinG: 20.8,
    servingFatG: 8.2,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'kuritsa-grudka': {
    key: 'kuritsa-grudka',
    servingSizeG: 100,
    servingCalories: 113,
    servingProteinG: 23.6,
    servingFatG: 1.9,
    servingCarbsG: 0.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kurkuma: {
    key: 'kurkuma',
    servingSizeG: 100,
    servingCalories: 312,
    servingProteinG: 9.7,
    servingFatG: 3.2,
    servingCarbsG: 67.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kuskus: {
    key: 'kuskus',
    servingSizeG: 100,
    servingCalories: 376,
    servingProteinG: 12.8,
    servingFatG: 0.6,
    servingCarbsG: 77.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  kvas: {
    key: 'kvas',
    servingSizeG: 100,
    servingCalories: 27,
    servingProteinG: 0.2,
    servingFatG: 0,
    servingCarbsG: 5.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'lapsha-risovaya': {
    key: 'lapsha-risovaya',
    servingSizeG: 100,
    servingCalories: 358,
    servingProteinG: 3.5,
    servingFatG: 0.5,
    servingCarbsG: 83,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'lapsha-udon': {
    key: 'lapsha-udon',
    servingSizeG: 100,
    servingCalories: 343,
    servingProteinG: 9,
    servingFatG: 1.2,
    servingCarbsG: 74,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'lapsha-yaichnaya': {
    key: 'lapsha-yaichnaya',
    servingSizeG: 100,
    servingCalories: 380,
    servingProteinG: 14,
    servingFatG: 4.5,
    servingCarbsG: 70,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'lavrovyy-list': {
    key: 'lavrovyy-list',
    servingSizeG: 100,
    servingCalories: 313,
    servingProteinG: 7.6,
    servingFatG: 8.4,
    servingCarbsG: 74.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  laym: {
    key: 'laym',
    servingSizeG: 100,
    servingCalories: 30,
    servingProteinG: 0.7,
    servingFatG: 0.2,
    servingCarbsG: 10.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  led: {
    key: 'led',
    servingSizeG: 100,
    servingCalories: 0,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  limon: {
    key: 'limon',
    servingSizeG: 100,
    servingCalories: 29,
    servingProteinG: 1.1,
    servingFatG: 0.3,
    servingCarbsG: 3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  limonad: {
    key: 'limonad',
    servingSizeG: 100,
    servingCalories: 42,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 10.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'luk-krasnyy': {
    key: 'luk-krasnyy',
    servingSizeG: 100,
    servingCalories: 42,
    servingProteinG: 1.1,
    servingFatG: 0.1,
    servingCarbsG: 9.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'luk-porey': {
    key: 'luk-porey',
    servingSizeG: 100,
    servingCalories: 36,
    servingProteinG: 2,
    servingFatG: 0.2,
    servingCarbsG: 8.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'luk-repchatyy': {
    key: 'luk-repchatyy',
    servingSizeG: 100,
    servingCalories: 41,
    servingProteinG: 1.1,
    servingFatG: 0.1,
    servingCarbsG: 9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  mak: {
    key: 'mak',
    servingSizeG: 100,
    servingCalories: 525,
    servingProteinG: 17.9,
    servingFatG: 47.5,
    servingCarbsG: 28.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  makarony: {
    key: 'makarony',
    servingSizeG: 100,
    servingCalories: 337,
    servingProteinG: 10.4,
    servingFatG: 1.1,
    servingCarbsG: 74.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  malina: {
    key: 'malina',
    servingSizeG: 100,
    servingCalories: 46,
    servingProteinG: 1.2,
    servingFatG: 0.7,
    servingCarbsG: 11.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  mango: {
    key: 'mango',
    servingSizeG: 100,
    servingCalories: 60,
    servingProteinG: 0.8,
    servingFatG: 0.4,
    servingCarbsG: 15,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  margarin: {
    key: 'margarin',
    servingSizeG: 100,
    servingCalories: 717,
    servingProteinG: 0.3,
    servingFatG: 82,
    servingCarbsG: 0.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  marmelad: {
    key: 'marmelad',
    servingSizeG: 100,
    servingCalories: 321,
    servingProteinG: 0,
    servingFatG: 0.2,
    servingCarbsG: 79.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  masliny: {
    key: 'masliny',
    servingSizeG: 100,
    servingCalories: 145,
    servingProteinG: 1,
    servingFatG: 15.1,
    servingCarbsG: 3.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'maslo-slivochnoe': {
    key: 'maslo-slivochnoe',
    servingSizeG: 100,
    servingCalories: 748,
    servingProteinG: 0.5,
    servingFatG: 82.5,
    servingCarbsG: 0.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  mayonez: {
    key: 'mayonez',
    servingSizeG: 100,
    servingCalories: 627,
    servingProteinG: 2.4,
    servingFatG: 67.3,
    servingCarbsG: 3.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  mayoran: {
    key: 'mayoran',
    servingSizeG: 100,
    servingCalories: 271,
    servingProteinG: 12.7,
    servingFatG: 7.1,
    servingCarbsG: 60.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  med: {
    key: 'med',
    servingSizeG: 100,
    servingCalories: 329,
    servingProteinG: 0.8,
    servingFatG: 0,
    servingCarbsG: 81.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  mindal: {
    key: 'mindal',
    servingSizeG: 100,
    servingCalories: 579,
    servingProteinG: 21.2,
    servingFatG: 49.9,
    servingCarbsG: 21.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'mineralnaya-voda': {
    key: 'mineralnaya-voda',
    servingSizeG: 100,
    servingCalories: 0,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'moloko-korove': {
    key: 'moloko-korove',
    servingSizeG: 100,
    servingCalories: 60,
    servingProteinG: 3.2,
    servingFatG: 3.6,
    servingCarbsG: 4.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'moloko-koze': {
    key: 'moloko-koze',
    servingSizeG: 100,
    servingCalories: 68,
    servingProteinG: 3.6,
    servingFatG: 4.1,
    servingCarbsG: 4.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'moloko-ovsyanoe': {
    key: 'moloko-ovsyanoe',
    servingSizeG: 100,
    servingCalories: 45,
    servingProteinG: 1,
    servingFatG: 1.5,
    servingCarbsG: 7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  morkov: {
    key: 'morkov',
    servingSizeG: 100,
    servingCalories: 35,
    servingProteinG: 1.3,
    servingFatG: 0.1,
    servingCarbsG: 6.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  morozhenoe: {
    key: 'morozhenoe',
    servingSizeG: 100,
    servingCalories: 207,
    servingProteinG: 3.5,
    servingFatG: 11,
    servingCarbsG: 23.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  mors: {
    key: 'mors',
    servingSizeG: 100,
    servingCalories: 41,
    servingProteinG: 0.1,
    servingFatG: 0,
    servingCarbsG: 10.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'muka-kukuruznaya': {
    key: 'muka-kukuruznaya',
    servingSizeG: 100,
    servingCalories: 331,
    servingProteinG: 7.2,
    servingFatG: 1.4,
    servingCarbsG: 73.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'muka-pshenichnaya': {
    key: 'muka-pshenichnaya',
    servingSizeG: 100,
    servingCalories: 342,
    servingProteinG: 10.3,
    servingFatG: 1.1,
    servingCarbsG: 68.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'muka-rzhanaya': {
    key: 'muka-rzhanaya',
    servingSizeG: 100,
    servingCalories: 337,
    servingProteinG: 10.7,
    servingFatG: 1.9,
    servingCarbsG: 61.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'muskatnyy-oreh': {
    key: 'muskatnyy-oreh',
    servingSizeG: 100,
    servingCalories: 525,
    servingProteinG: 5.8,
    servingFatG: 36.3,
    servingCarbsG: 49.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'myata-sushenaya': {
    key: 'myata-sushenaya',
    servingSizeG: 100,
    servingCalories: 70,
    servingProteinG: 3.8,
    servingFatG: 0.7,
    servingCarbsG: 15,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  myusli: {
    key: 'myusli',
    servingSizeG: 100,
    servingCalories: 380,
    servingProteinG: 10,
    servingFatG: 7,
    servingCarbsG: 66,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  oblepiha: {
    key: 'oblepiha',
    servingSizeG: 100,
    servingCalories: 82,
    servingProteinG: 1.2,
    servingFatG: 5.4,
    servingCarbsG: 5.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  ogurets: {
    key: 'ogurets',
    servingSizeG: 100,
    servingCalories: 15,
    servingProteinG: 0.8,
    servingFatG: 0.1,
    servingCarbsG: 2.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  olivki: {
    key: 'olivki',
    servingSizeG: 100,
    servingCalories: 115,
    servingProteinG: 0.8,
    servingFatG: 10.7,
    servingCarbsG: 6.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  oregano: {
    key: 'oregano',
    servingSizeG: 100,
    servingCalories: 265,
    servingProteinG: 9,
    servingFatG: 4.3,
    servingCarbsG: 68.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'orehi-gretskie': {
    key: 'orehi-gretskie',
    servingSizeG: 100,
    servingCalories: 654,
    servingProteinG: 15.2,
    servingFatG: 65.2,
    servingCarbsG: 13.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  ovsyanka: {
    key: 'ovsyanka',
    servingSizeG: 100,
    servingCalories: 366,
    servingProteinG: 12.3,
    servingFatG: 6.2,
    servingCarbsG: 61,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  paprika: {
    key: 'paprika',
    servingSizeG: 100,
    servingCalories: 282,
    servingProteinG: 14.1,
    servingFatG: 12.9,
    servingCarbsG: 53.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  pastila: {
    key: 'pastila',
    servingSizeG: 100,
    servingCalories: 310,
    servingProteinG: 0.5,
    servingFatG: 0,
    servingCarbsG: 80.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'pechen-govyazhya': {
    key: 'pechen-govyazhya',
    servingSizeG: 100,
    servingCalories: 127,
    servingProteinG: 19.8,
    servingFatG: 3.6,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  pechene: {
    key: 'pechene',
    servingSizeG: 100,
    servingCalories: 417,
    servingProteinG: 7.5,
    servingFatG: 9.5,
    servingCarbsG: 75,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  pelmeni: {
    key: 'pelmeni',
    servingSizeG: 100,
    servingCalories: 245,
    servingProteinG: 11.9,
    servingFatG: 8.4,
    servingCarbsG: 32,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  penne: {
    key: 'penne',
    servingSizeG: 100,
    servingCalories: 358,
    servingProteinG: 12.5,
    servingFatG: 1.5,
    servingCarbsG: 78.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'perets-bolgarskiy': {
    key: 'perets-bolgarskiy',
    servingSizeG: 100,
    servingCalories: 27,
    servingProteinG: 1.3,
    servingFatG: 0.1,
    servingCarbsG: 5.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'perets-chernyy': {
    key: 'perets-chernyy',
    servingSizeG: 100,
    servingCalories: 251,
    servingProteinG: 10.4,
    servingFatG: 3.3,
    servingCarbsG: 63.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'perets-chili': {
    key: 'perets-chili',
    servingSizeG: 100,
    servingCalories: 40,
    servingProteinG: 1.9,
    servingFatG: 0.4,
    servingCarbsG: 8.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'perets-krasnyy': {
    key: 'perets-krasnyy',
    servingSizeG: 100,
    servingCalories: 40,
    servingProteinG: 2.5,
    servingFatG: 0.5,
    servingCarbsG: 7.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  perlovka: {
    key: 'perlovka',
    servingSizeG: 100,
    servingCalories: 320,
    servingProteinG: 9.3,
    servingFatG: 1.1,
    servingCarbsG: 73.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  petrushka: {
    key: 'petrushka',
    servingSizeG: 100,
    servingCalories: 49,
    servingProteinG: 3.7,
    servingFatG: 0.4,
    servingCarbsG: 7.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'podsolnechnye-semechki': {
    key: 'podsolnechnye-semechki',
    servingSizeG: 100,
    servingCalories: 578,
    servingProteinG: 20.8,
    servingFatG: 52.5,
    servingCarbsG: 20,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  pomidor: {
    key: 'pomidor',
    servingSizeG: 100,
    servingCalories: 20,
    servingProteinG: 1.1,
    servingFatG: 0.2,
    servingCarbsG: 3.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'pomidory-cherri': {
    key: 'pomidory-cherri',
    servingSizeG: 100,
    servingCalories: 20,
    servingProteinG: 1.1,
    servingFatG: 0.2,
    servingCarbsG: 3.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  popkorn: {
    key: 'popkorn',
    servingSizeG: 100,
    servingCalories: 401,
    servingProteinG: 7.9,
    servingFatG: 4.5,
    servingCarbsG: 78.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  prostokvasha: {
    key: 'prostokvasha',
    servingSizeG: 100,
    servingCalories: 58,
    servingProteinG: 2.8,
    servingFatG: 3.2,
    servingCarbsG: 4.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  psheno: {
    key: 'psheno',
    servingSizeG: 100,
    servingCalories: 348,
    servingProteinG: 11.5,
    servingFatG: 3.3,
    servingCarbsG: 69.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  razryhlitel: {
    key: 'razryhlitel',
    servingSizeG: 100,
    servingCalories: 0,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  redis: {
    key: 'redis',
    servingSizeG: 100,
    servingCalories: 20,
    servingProteinG: 1.2,
    servingFatG: 0.1,
    servingCarbsG: 3.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'ris-basmati': {
    key: 'ris-basmati',
    servingSizeG: 100,
    servingCalories: 349,
    servingProteinG: 8.1,
    servingFatG: 0.6,
    servingCarbsG: 80,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'ris-belyy': {
    key: 'ris-belyy',
    servingSizeG: 100,
    servingCalories: 344,
    servingProteinG: 6.7,
    servingFatG: 0.7,
    servingCarbsG: 78,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'ris-buryy': {
    key: 'ris-buryy',
    servingSizeG: 100,
    servingCalories: 337,
    servingProteinG: 7.4,
    servingFatG: 2.7,
    servingCarbsG: 77.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  rozmarin: {
    key: 'rozmarin',
    servingSizeG: 100,
    servingCalories: 131,
    servingProteinG: 3.3,
    servingFatG: 5.9,
    servingCarbsG: 20.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  rukkola: {
    key: 'rukkola',
    servingSizeG: 100,
    servingCalories: 25,
    servingProteinG: 2.6,
    servingFatG: 0.7,
    servingCarbsG: 2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  ryazhenka: {
    key: 'ryazhenka',
    servingSizeG: 100,
    servingCalories: 67,
    servingProteinG: 3,
    servingFatG: 4,
    servingCarbsG: 4.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'rybnyy-sous': {
    key: 'rybnyy-sous',
    servingSizeG: 100,
    servingCalories: 35,
    servingProteinG: 5,
    servingFatG: 0,
    servingCarbsG: 2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  sahar: {
    key: 'sahar',
    servingSizeG: 100,
    servingCalories: 387,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 99.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'salat-aysberg': {
    key: 'salat-aysberg',
    servingSizeG: 100,
    servingCalories: 14,
    servingProteinG: 0.9,
    servingFatG: 0.1,
    servingCarbsG: 3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  schavel: {
    key: 'schavel',
    servingSizeG: 100,
    servingCalories: 22,
    servingProteinG: 1.5,
    servingFatG: 0.4,
    servingCarbsG: 3.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  selderey: {
    key: 'selderey',
    servingSizeG: 100,
    servingCalories: 16,
    servingProteinG: 0.7,
    servingFatG: 0.2,
    servingCarbsG: 3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'semena-chia': {
    key: 'semena-chia',
    servingSizeG: 100,
    servingCalories: 486,
    servingProteinG: 16.5,
    servingFatG: 30.7,
    servingCarbsG: 42.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'semena-lna': {
    key: 'semena-lna',
    servingSizeG: 100,
    servingCalories: 534,
    servingProteinG: 18.3,
    servingFatG: 42.2,
    servingCarbsG: 28.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'serdtse-govyazhe': {
    key: 'serdtse-govyazhe',
    servingSizeG: 100,
    servingCalories: 112,
    servingProteinG: 17.9,
    servingFatG: 4.3,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  sguschenka: {
    key: 'sguschenka',
    servingSizeG: 100,
    servingCalories: 320,
    servingProteinG: 6,
    servingFatG: 8.5,
    servingCarbsG: 54,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  shafran: {
    key: 'shafran',
    servingSizeG: 100,
    servingCalories: 310,
    servingProteinG: 11.4,
    servingFatG: 5.9,
    servingCarbsG: 65.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  shipovnik: {
    key: 'shipovnik',
    servingSizeG: 100,
    servingCalories: 109,
    servingProteinG: 1.6,
    servingFatG: 0.7,
    servingCarbsG: 24,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'shokolad-belyy': {
    key: 'shokolad-belyy',
    servingSizeG: 100,
    servingCalories: 539,
    servingProteinG: 5.9,
    servingFatG: 33.2,
    servingCarbsG: 58.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'shokolad-chernyy': {
    key: 'shokolad-chernyy',
    servingSizeG: 100,
    servingCalories: 546,
    servingProteinG: 6.2,
    servingFatG: 35.4,
    servingCarbsG: 48.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'shokolad-molochnyy': {
    key: 'shokolad-molochnyy',
    servingSizeG: 100,
    servingCalories: 535,
    servingProteinG: 7.6,
    servingFatG: 30,
    servingCarbsG: 59.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  shpinat: {
    key: 'shpinat',
    servingSizeG: 100,
    servingCalories: 23,
    servingProteinG: 2.9,
    servingFatG: 0.4,
    servingCarbsG: 3.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'slivki-10': {
    key: 'slivki-10',
    servingSizeG: 100,
    servingCalories: 118,
    servingProteinG: 2.8,
    servingFatG: 10,
    servingCarbsG: 3.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'slivki-20': {
    key: 'slivki-20',
    servingSizeG: 100,
    servingCalories: 205,
    servingProteinG: 2.5,
    servingFatG: 20,
    servingCarbsG: 3.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'slivki-33': {
    key: 'slivki-33',
    servingSizeG: 100,
    servingCalories: 322,
    servingProteinG: 2.2,
    servingFatG: 33,
    servingCarbsG: 3.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'smetana-15': {
    key: 'smetana-15',
    servingSizeG: 100,
    servingCalories: 158,
    servingProteinG: 2.6,
    servingFatG: 15,
    servingCarbsG: 3.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'smetana-20': {
    key: 'smetana-20',
    servingSizeG: 100,
    servingCalories: 204,
    servingProteinG: 2.8,
    servingFatG: 20,
    servingCarbsG: 3.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'smetana-25': {
    key: 'smetana-25',
    servingSizeG: 100,
    servingCalories: 248,
    servingProteinG: 2.6,
    servingFatG: 25,
    servingCarbsG: 2.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'smorodina-chernaya': {
    key: 'smorodina-chernaya',
    servingSizeG: 100,
    servingCalories: 44,
    servingProteinG: 1.4,
    servingFatG: 0.4,
    servingCarbsG: 13.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  soda: {
    key: 'soda',
    servingSizeG: 100,
    servingCalories: 0,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'soevyy-sous': {
    key: 'soevyy-sous',
    servingSizeG: 100,
    servingCalories: 53,
    servingProteinG: 8.1,
    servingFatG: 0.1,
    servingCarbsG: 4.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'sok-apelsinovyy': {
    key: 'sok-apelsinovyy',
    servingSizeG: 100,
    servingCalories: 45,
    servingProteinG: 0.7,
    servingFatG: 0.2,
    servingCarbsG: 10.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'sok-tomatnyy': {
    key: 'sok-tomatnyy',
    servingSizeG: 100,
    servingCalories: 17,
    servingProteinG: 0.8,
    servingFatG: 0.1,
    servingCarbsG: 3.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'sok-yablochnyy': {
    key: 'sok-yablochnyy',
    servingSizeG: 100,
    servingCalories: 46,
    servingProteinG: 0.1,
    servingFatG: 0.1,
    servingCarbsG: 11.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  sol: {
    key: 'sol',
    servingSizeG: 100,
    servingCalories: 0,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  sosiski: {
    key: 'sosiski',
    servingSizeG: 100,
    servingCalories: 266,
    servingProteinG: 11.3,
    servingFatG: 24.3,
    servingCarbsG: 1.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'sous-chili': {
    key: 'sous-chili',
    servingSizeG: 100,
    servingCalories: 93,
    servingProteinG: 1.4,
    servingFatG: 0.6,
    servingCarbsG: 21,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'sous-teriyaki': {
    key: 'sous-teriyaki',
    servingSizeG: 100,
    servingCalories: 89,
    servingProteinG: 5.9,
    servingFatG: 0,
    servingCarbsG: 15.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  spagetti: {
    key: 'spagetti',
    servingSizeG: 100,
    servingCalories: 344,
    servingProteinG: 11.8,
    servingFatG: 1.4,
    servingCarbsG: 74.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'suhari-panirovochnye': {
    key: 'suhari-panirovochnye',
    servingSizeG: 100,
    servingCalories: 350,
    servingProteinG: 9.7,
    servingFatG: 4.7,
    servingCarbsG: 68,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  suhofrukty: {
    key: 'suhofrukty',
    servingSizeG: 100,
    servingCalories: 283,
    servingProteinG: 3.1,
    servingFatG: 0.7,
    servingCarbsG: 68,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  sushki: {
    key: 'sushki',
    servingSizeG: 100,
    servingCalories: 342,
    servingProteinG: 10.9,
    servingFatG: 3.2,
    servingCarbsG: 70.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  svekla: {
    key: 'svekla',
    servingSizeG: 100,
    servingCalories: 43,
    servingProteinG: 1.6,
    servingFatG: 0.2,
    servingCarbsG: 10,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'svinina-farsh': {
    key: 'svinina-farsh',
    servingSizeG: 100,
    servingCalories: 263,
    servingProteinG: 16.9,
    servingFatG: 21.6,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'svinina-vyrezka': {
    key: 'svinina-vyrezka',
    servingSizeG: 100,
    servingCalories: 142,
    servingProteinG: 20.4,
    servingFatG: 6.4,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'syr-bri': {
    key: 'syr-bri',
    servingSizeG: 100,
    servingCalories: 317,
    servingProteinG: 21,
    servingFatG: 24,
    servingCarbsG: 0.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'syr-chedder': {
    key: 'syr-chedder',
    servingSizeG: 100,
    servingCalories: 392,
    servingProteinG: 25,
    servingFatG: 33,
    servingCarbsG: 1.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'syr-dor-blyu': {
    key: 'syr-dor-blyu',
    servingSizeG: 100,
    servingCalories: 364,
    servingProteinG: 21,
    servingFatG: 30,
    servingCarbsG: 2.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'syr-feta': {
    key: 'syr-feta',
    servingSizeG: 100,
    servingCalories: 264,
    servingProteinG: 14,
    servingFatG: 21,
    servingCarbsG: 4.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'syr-gauda': {
    key: 'syr-gauda',
    servingSizeG: 100,
    servingCalories: 356,
    servingProteinG: 25,
    servingFatG: 27,
    servingCarbsG: 2.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'syr-maskarpone': {
    key: 'syr-maskarpone',
    servingSizeG: 100,
    servingCalories: 450,
    servingProteinG: 4.8,
    servingFatG: 44,
    servingCarbsG: 4.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'syr-motsarella': {
    key: 'syr-motsarella',
    servingSizeG: 100,
    servingCalories: 280,
    servingProteinG: 28,
    servingFatG: 17,
    servingCarbsG: 3.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'syr-parmezan': {
    key: 'syr-parmezan',
    servingSizeG: 100,
    servingCalories: 392,
    servingProteinG: 33,
    servingFatG: 28,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'syr-rikotta': {
    key: 'syr-rikotta',
    servingSizeG: 100,
    servingCalories: 174,
    servingProteinG: 11,
    servingFatG: 13,
    servingCarbsG: 3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'syr-rossiyskiy': {
    key: 'syr-rossiyskiy',
    servingSizeG: 100,
    servingCalories: 363,
    servingProteinG: 24,
    servingFatG: 29,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  tahini: {
    key: 'tahini',
    servingSizeG: 100,
    servingCalories: 595,
    servingProteinG: 17,
    servingFatG: 53.8,
    servingCarbsG: 21.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  telyatina: {
    key: 'telyatina',
    servingSizeG: 100,
    servingCalories: 131,
    servingProteinG: 20.4,
    servingFatG: 5.4,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  timyan: {
    key: 'timyan',
    servingSizeG: 100,
    servingCalories: 101,
    servingProteinG: 5.6,
    servingFatG: 1.7,
    servingCarbsG: 10.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  tmin: {
    key: 'tmin',
    servingSizeG: 100,
    servingCalories: 333,
    servingProteinG: 17.8,
    servingFatG: 14.6,
    servingCarbsG: 44.2,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  tolokno: {
    key: 'tolokno',
    servingSizeG: 100,
    servingCalories: 363,
    servingProteinG: 12.5,
    servingFatG: 6.2,
    servingCarbsG: 64,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'tomatnaya-pasta': {
    key: 'tomatnaya-pasta',
    servingSizeG: 100,
    servingCalories: 82,
    servingProteinG: 4.3,
    servingFatG: 0.5,
    servingCarbsG: 15.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'tomatnyy-sous': {
    key: 'tomatnyy-sous',
    servingSizeG: 100,
    servingCalories: 29,
    servingProteinG: 1.3,
    servingFatG: 0.2,
    servingCarbsG: 5.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  tsukaty: {
    key: 'tsukaty',
    servingSizeG: 100,
    servingCalories: 343,
    servingProteinG: 1.6,
    servingFatG: 0.2,
    servingCarbsG: 83.4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  tvorog: {
    key: 'tvorog',
    servingSizeG: 100,
    servingCalories: 121,
    servingProteinG: 17.2,
    servingFatG: 5,
    servingCarbsG: 1.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'tvorog-5': {
    key: 'tvorog-5',
    servingSizeG: 100,
    servingCalories: 121,
    servingProteinG: 17.2,
    servingFatG: 5,
    servingCarbsG: 1.8,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'tvorog-9': {
    key: 'tvorog-9',
    servingSizeG: 100,
    servingCalories: 159,
    servingProteinG: 18,
    servingFatG: 9,
    servingCarbsG: 3.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'tvorog-obezzhirennyy': {
    key: 'tvorog-obezzhirennyy',
    servingSizeG: 100,
    servingCalories: 71,
    servingProteinG: 16.5,
    servingFatG: 0.1,
    servingCarbsG: 1.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  tykva: {
    key: 'tykva',
    servingSizeG: 100,
    servingCalories: 28,
    servingProteinG: 1,
    servingFatG: 0.1,
    servingCarbsG: 7.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'tykvennye-semechki': {
    key: 'tykvennye-semechki',
    servingSizeG: 100,
    servingCalories: 541,
    servingProteinG: 24.5,
    servingFatG: 45.8,
    servingCarbsG: 14.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  ukrop: {
    key: 'ukrop',
    servingSizeG: 100,
    servingCalories: 43,
    servingProteinG: 3.5,
    servingFatG: 0.5,
    servingCarbsG: 6.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'uksus-balzamicheskiy': {
    key: 'uksus-balzamicheskiy',
    servingSizeG: 100,
    servingCalories: 88,
    servingProteinG: 0.5,
    servingFatG: 0,
    servingCarbsG: 17,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'uksus-stolovyy': {
    key: 'uksus-stolovyy',
    servingSizeG: 100,
    servingCalories: 21,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 0.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'uksus-yablochnyy': {
    key: 'uksus-yablochnyy',
    servingSizeG: 100,
    servingCalories: 21,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 0.9,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  utka: {
    key: 'utka',
    servingSizeG: 100,
    servingCalories: 308,
    servingProteinG: 18.3,
    servingFatG: 25.8,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  vanil: {
    key: 'vanil',
    servingSizeG: 100,
    servingCalories: 288,
    servingProteinG: 0.1,
    servingFatG: 0.1,
    servingCarbsG: 12.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  varene: {
    key: 'varene',
    servingSizeG: 100,
    servingCalories: 278,
    servingProteinG: 0.3,
    servingFatG: 0,
    servingCarbsG: 71,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  vetchina: {
    key: 'vetchina',
    servingSizeG: 100,
    servingCalories: 216,
    servingProteinG: 14.9,
    servingFatG: 16.7,
    servingCarbsG: 1.5,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'vino-beloe': {
    key: 'vino-beloe',
    servingSizeG: 100,
    servingCalories: 82,
    servingProteinG: 0.1,
    servingFatG: 0,
    servingCarbsG: 2.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'vino-krasnoe': {
    key: 'vino-krasnoe',
    servingSizeG: 100,
    servingCalories: 85,
    servingProteinG: 0.1,
    servingFatG: 0,
    servingCarbsG: 2.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  vinograd: {
    key: 'vinograd',
    servingSizeG: 100,
    servingCalories: 69,
    servingProteinG: 0.7,
    servingFatG: 0.2,
    servingCarbsG: 18,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  vishnya: {
    key: 'vishnya',
    servingSizeG: 100,
    servingCalories: 52,
    servingProteinG: 1,
    servingFatG: 0.3,
    servingCarbsG: 10.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  voda: {
    key: 'voda',
    servingSizeG: 100,
    servingCalories: 0,
    servingProteinG: 0,
    servingFatG: 0,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  yabloko: {
    key: 'yabloko',
    servingSizeG: 100,
    servingCalories: 52,
    servingProteinG: 0.3,
    servingFatG: 0.2,
    servingCarbsG: 14,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'yaytso-kurinoe': {
    key: 'yaytso-kurinoe',
    servingSizeG: 100,
    servingCalories: 157,
    servingProteinG: 12.7,
    servingFatG: 11.5,
    servingCarbsG: 0.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'yaytso-perepelinoe': {
    key: 'yaytso-perepelinoe',
    servingSizeG: 100,
    servingCalories: 168,
    servingProteinG: 11.9,
    servingFatG: 13.1,
    servingCarbsG: 0.6,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  yazyk: {
    key: 'yazyk',
    servingSizeG: 100,
    servingCalories: 208,
    servingProteinG: 14.2,
    servingFatG: 16.8,
    servingCarbsG: 0,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'yogurt-grecheskiy': {
    key: 'yogurt-grecheskiy',
    servingSizeG: 100,
    servingCalories: 97,
    servingProteinG: 9,
    servingFatG: 5,
    servingCarbsG: 4,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  'yogurt-naturalnyy': {
    key: 'yogurt-naturalnyy',
    servingSizeG: 100,
    servingCalories: 68,
    servingProteinG: 5,
    servingFatG: 3.5,
    servingCarbsG: 4.3,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  zefir: {
    key: 'zefir',
    servingSizeG: 100,
    servingCalories: 326,
    servingProteinG: 0.8,
    servingFatG: 0.1,
    servingCarbsG: 81.1,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
  zhelatin: {
    key: 'zhelatin',
    servingSizeG: 100,
    servingCalories: 335,
    servingProteinG: 85,
    servingFatG: 0.2,
    servingCarbsG: 0.7,
    source: 'USDA',
    sourceUpdatedAt: '2026-09-01',
  },
};
