-- Rollback mc089 (ADR-0023 phase 3 wave-2): деактивировать RLS на
-- таблицах, включённых этой миграцией (PantryItem был раньше — mc088).
ALTER TABLE "MealPlan" NO FORCE ROW LEVEL SECURITY; ALTER TABLE "MealPlan" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "MealPlanDay" NO FORCE ROW LEVEL SECURITY; ALTER TABLE "MealPlanDay" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "MealPlanEntry" NO FORCE ROW LEVEL SECURITY; ALTER TABLE "MealPlanEntry" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PrepSession" NO FORCE ROW LEVEL SECURITY; ALTER TABLE "PrepSession" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PrepTask" NO FORCE ROW LEVEL SECURITY; ALTER TABLE "PrepTask" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ShoppingList" NO FORCE ROW LEVEL SECURITY; ALTER TABLE "ShoppingList" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ShoppingListItem" NO FORCE ROW LEVEL SECURITY; ALTER TABLE "ShoppingListItem" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Preference" NO FORCE ROW LEVEL SECURITY; ALTER TABLE "Preference" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "NutritionProfile" NO FORCE ROW LEVEL SECURITY; ALTER TABLE "NutritionProfile" DISABLE ROW LEVEL SECURITY;
